import SwiftUI
import Combine

/// Central app state management
@MainActor
final class AppState: ObservableObject {
    static let shared = AppState()

    // MARK: - Navigation

    enum Tab: String, CaseIterable, Identifiable {
        case dashboard
        case history
        case sources
        case settings

        var id: String { rawValue }

        var title: String {
            switch self {
            case .dashboard: return "Briefing"
            case .history: return "Verlauf"
            case .sources: return "Quellen"
            case .settings: return "Einstellungen"
            }
        }

        var icon: String {
            switch self {
            case .dashboard: return "sun.horizon.fill"
            case .history: return "clock.arrow.circlepath"
            case .sources: return "square.stack.3d.up.fill"
            case .settings: return "gearshape.fill"
            }
        }
    }

    @Published var selectedTab: Tab = .dashboard
    @Published var showOnboarding: Bool = false

    // MARK: - Briefing State

    @Published var isLoadingBriefing: Bool = false
    @Published var isPlayingAudio: Bool = false
    @Published var currentBriefing: Briefing?
    @Published var generationProgress: GenerationProgress = .idle
    @Published var lastError: BriefingGenerationError?
    @Published var showError: Bool = false

    // MARK: - Network State

    @Published var isOnline: Bool = true

    // MARK: - Source Management

    @Published var connectedSources: [any BriefingSource] = []
    @Published var availableSources: [any BriefingSource.Type] = []

    // MARK: - Services

    private let briefingService = BriefingGenerationService.shared
    private let schedulingService = SchedulingService.shared
    private let shortcutService = GlobalShortcutService.shared
    private let ttsService = TTSService.shared
    private let networkMonitor = NetworkMonitor.shared
    private let cacheService = BriefingCacheService.shared
    private let recordingService = AudioRecordingService.shared
    private var cancellables = Set<AnyCancellable>()

    // MARK: - Initialization

    init() {
        checkOnboardingStatus()
        setupServiceBindings()
        setupSchedulingCallbacks()
        setupShortcutCallbacks()
        setupTTSBindings()
        setupNetworkBindings()
        setupRecordingHUDCallbacks()
    }

    private func checkOnboardingStatus() {
        let hasCompletedOnboarding = UserDefaults.standard.bool(forKey: "hasCompletedOnboarding")
        showOnboarding = !hasCompletedOnboarding
    }

    func completeOnboarding() {
        UserDefaults.standard.set(true, forKey: "hasCompletedOnboarding")
        showOnboarding = false
    }

    // MARK: - Service Bindings

    private func setupServiceBindings() {
        // Bind briefing service state to app state
        briefingService.$isGenerating
            .receive(on: DispatchQueue.main)
            .assign(to: &$isLoadingBriefing)

        briefingService.$generationProgress
            .receive(on: DispatchQueue.main)
            .assign(to: &$generationProgress)

        briefingService.$lastError
            .receive(on: DispatchQueue.main)
            .sink { [weak self] error in
                self?.lastError = error
                if error != nil {
                    self?.showError = true
                }
            }
            .store(in: &cancellables)
    }

    private func setupSchedulingCallbacks() {
        // Handle briefings generated by the scheduling service
        schedulingService.onBriefingGenerated = { [weak self] briefing in
            Task { @MainActor in
                self?.currentBriefing = briefing
            }
        }

        schedulingService.onBriefingFailed = { [weak self] error in
            Task { @MainActor in
                if let briefingError = error as? BriefingGenerationError {
                    self?.lastError = briefingError
                } else {
                    self?.lastError = .unknown(error)
                }
                self?.showError = true
            }
        }
    }

    private func setupShortcutCallbacks() {
        // Handle global keyboard shortcut trigger
        shortcutService.onShortcutTriggered = { [weak self] in
            Task { @MainActor in
                await self?.refreshBriefing()
                // Bring app to front
                NSApplication.shared.activate(ignoringOtherApps: true)
            }
        }
    }

    private func setupTTSBindings() {
        // Bind TTS playing state to app state
        ttsService.$isPlaying
            .receive(on: DispatchQueue.main)
            .assign(to: &$isPlayingAudio)
    }

    private func setupNetworkBindings() {
        // Bind network monitor state to app state
        networkMonitor.$isOnline
            .receive(on: DispatchQueue.main)
            .assign(to: &$isOnline)
    }

    // MARK: - Briefing Actions

    /// Generate a new briefing
    func refreshBriefing(detailLevel: Briefing.DetailLevel = .quick) async {
        do {
            let briefing = try await briefingService.generateBriefing(detailLevel: detailLevel)
            currentBriefing = briefing
            showError = false
        } catch {
            // Error handling is done via the service binding
        }
    }

    /// Dismiss the error alert
    func dismissError() {
        showError = false
        lastError = nil
    }

    /// Load the most recent cached briefing (for offline mode)
    func loadCachedBriefing() {
        if let cached = cacheService.loadLatest() {
            currentBriefing = cached
        }
    }

    /// Check if Ollama is available for offline generation
    func checkOllamaAvailability() async -> Bool {
        await networkMonitor.checkOllamaAvailability()
    }

    /// Whether Ollama is configured as the LLM provider
    var isOllamaConfigured: Bool {
        networkMonitor.isOllamaConfigured()
    }

    /// Whether there's a cached briefing available
    var hasCachedBriefing: Bool {
        cacheService.cachedBriefingCount > 0
    }

    func toggleAudioPlayback() {
        if ttsService.isPlaying || ttsService.isPaused {
            // If already playing or paused, toggle play/pause
            ttsService.togglePlayPause()
        } else if let briefing = currentBriefing {
            // Start speaking the briefing
            let textToSpeak = buildBriefingText(from: briefing)
            ttsService.speak(text: textToSpeak)
        }
    }

    func stopAudioPlayback() {
        ttsService.stop()
    }

    private func buildBriefingText(from briefing: Briefing) -> String {
        var text = briefing.summary

        for section in briefing.sections {
            text += "\n\n\(section.sourceName):\n"
            for item in section.items {
                text += "\(item.title). "
                if let subtitle = item.subtitle {
                    text += "\(subtitle). "
                }
            }
        }

        return text
    }

    // MARK: - Scheduling Control

    /// Enable automatic briefing scheduling
    func enableScheduling(at time: Date) {
        schedulingService.updateScheduledTime(time)
        schedulingService.enableScheduling()
    }

    /// Disable automatic briefing scheduling
    func disableScheduling() {
        schedulingService.disableScheduling()
    }

    var isSchedulingEnabled: Bool {
        schedulingService.isScheduled
    }

    var scheduledTime: Date {
        get { schedulingService.scheduledTime }
        set { schedulingService.updateScheduledTime(newValue) }
    }

    var nextScheduledBriefingTime: String? {
        schedulingService.formattedNextTime
    }

    // MARK: - Shortcut Control

    /// Enable global keyboard shortcut
    func enableGlobalShortcut() {
        shortcutService.enable()
    }

    /// Disable global keyboard shortcut
    func disableGlobalShortcut() {
        shortcutService.disable()
    }

    var isGlobalShortcutEnabled: Bool {
        shortcutService.isEnabled
    }

    var currentShortcut: KeyboardShortcut {
        get { shortcutService.currentShortcut }
        set { shortcutService.updateShortcut(newValue) }
    }

    // MARK: - Recording HUD Support

    private func setupRecordingHUDCallbacks() {
        NotificationCenter.default.addObserver(
            forName: .stopRecordingFromHUD,
            object: nil,
            queue: .main
        ) { [weak self] _ in
            Task { @MainActor in
                await self?.stopRecordingAndProcess()
            }
        }
    }

    private func stopRecordingAndProcess() async {
        guard let url = recordingService.stopRecording() else { return }
        
        // Show the app and navigate to meetings so user sees transcription
        NSApplication.shared.activate(ignoringOtherApps: true)
        selectedTab = .dashboard
        // We can't easily trigger the local state of MeetingsView from here
        // without a more centralized recording state manager.
        // For now, let's just make sure it's processed.
        
        // Since MeetingsView has its own state for transcription, 
        // it's better to move this logic to a service.
        // I will implement a basic version here and later refactor if needed.
        
        do {
            let transcription = try await TranscriptionService.shared.transcribe(audioURL: url)
            MeetingNotesService.shared.createAdHocMeeting(notes: transcription)
            try? FileManager.default.removeItem(at: url)
        } catch {
            print("Failed to transcribe HUD recording: \(error)")
        }
    }
    
    // MARK: - Quick Action Support
    
    /// Save a quick note from the menu bar as an ad-hoc meeting
    func addQuickNote(_ text: String) {
        let title = "Notiz \(Date().formatted(date: .omitted, time: .shortened))"
        MeetingNotesService.shared.createAdHocMeeting(title: title, notes: text)
        
        // Optionally notify user or provide feedback
        // For now, we assume the UI will handle the "sent" state
    }
}
